name: My Self Service
run-name: ${{ github.actor }} is testing out GitHub Actions on rc1.0 branch 🚀

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World rc1.0"
